name: betterer-github-action
description: "It's a Betterer runner with custom minimal reporter"
branding:
  icon: "bar-chart"
  color: "red"
inputs:
  chatops_results_file_update_command:
    description: "Command that triggers .betterer.results file update"
    required: true
    default: "betterer:update"
  betterer_results_file_name:
    description: "Name or path of \".betterer.results\" file"
    required: true
    default: ".betterer.results"
outputs:
  fixed_issues_count:
    description: "Amount of fixed issues"
  new_issues_count:
    description: "Amount of newly introduced issues"
  fixed_issues:
    description: "List of fixed issues"
  new_issues:
    description: "List of newly introduced issues"
runs:
  using: "docker"
  image: "docker://evilweed88/betterer-github-action:latest"
